In [4]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle
import pandas as pd
import numpy as np

In [5]:
## Load the Trained model
model=load_model('model.h5')

In [ ]:
## Load the Feature Encoding pkl Files (Gender Column)
with open('lbl_encoder.pkl','rb') as file:  ## Read Byte
     lbl_encoder=pickle.load(file)

In [10]:
## Load the Feature Encoding pkl Files (Geography Column)
with open('ohe.pkl','rb') as file:  ## Read Byte
     ohe=pickle.load(file)

In [11]:
## Load Scaler file
with open('scaler.pkl','rb') as file:  ## Read Byte
     scaler=pickle.load(file)

In [22]:
## Example of input Data
input_data = {'CreditScore':600,'Geography':'France','Gender':'Male','Age':40,'Tenure':3,'Balance':60000,'NumOfProducts':2,'HasCrCard':1,'IsActiveMember':1,'EstimatedSalary':50000}

In [23]:
## Converting input data into Dataframe
input_df = pd.DataFrame([input_data])
input_df

CreditScore Geography Gender  Age  Tenure  Balance  NumOfProducts  \
0          600    France   Male   40       3    60000              2   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1            50000

In [24]:
## Converting Gender column into label
input_df['Gender'] = lbl_encoder.transform(input_df['Gender'])
input_df

CreditScore Geography  Gender  Age  Tenure  Balance  NumOfProducts  \
0          600    France       1   40       3    60000              2   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1            50000

In [25]:
## Converting Geography column into label
encoded_array = ohe.transform(input_df[['Geography']])
encoded_array

array([[1., 0., 0.]])

In [26]:
encoded_df = pd.DataFrame(encoded_array, columns=ohe.get_feature_names_out(['Geography']))
encoded_df

Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [27]:
input_df.drop('Geography',axis=1,inplace=True)
input_df = pd.concat([input_df, encoded_df], axis=1)
input_df

CreditScore  Gender  Age  Tenure  Balance  NumOfProducts  HasCrCard  \
0          600       1   40       3    60000              2          1   

   IsActiveMember  EstimatedSalary  Geography_France  Geography_Germany  \
0               1            50000               1.0                0.0   

   Geography_Spain  
0              0.0

In [28]:
## Scaling the data
input_df = scaler.transform(input_df)
input_df

array([[-0.53598516,  0.91324755,  0.10479359, -0.69539349, -0.25781119,
         0.80843615,  0.64920267,  0.97481699, -0.87683221,  1.00150113,
        -0.57946723, -0.57638802]])

In [31]:
## Prediction
prediction=model.predict(input_df)
prediction

1/1 [==============================] - 0s 13ms/step


array([[0.02281837]], dtype=float32)

In [35]:
prediction_prob = prediction[0][0]
prediction_prob

0.022818374

In [37]:
if prediction_prob > 0.5:
    print("Customer is likely to churn.")
else :
    print("Customer is not likelt to churn.")

Customer is not likelt to churn.
